### ISSUE TITLE
Help numerary help @beartype (help numerary) by porting CachingProtocolMeta to beartype

### ISSUE THREAD

**Issue by posita** [posita/numerary#8]
Original proposal attributed to @leycyc. From https://github.com/posita/numerary/issues/7#issuecomment-1017219264:

> **Diversionary trainwreck alert:** you have implemented something suspiciously fast and dangerously beautiful with the homegrown private caching protocol API (HPCPAPI) that is the beating heart of `numerary`. Would incorporating that API directly into `beartype` itself be feasible?
> 
> Here is what I am cogitating. `typing.Protocol` is slower than good ol' Southern molasses. `beartype.typing.Protocol` is currently just a trivial alias for `typing.Protocol` and thus also slower than that foodstuff. `beartype.typing.Protocol` doesn't _need_ to be a trivial alias, however; in theory, `beartype.typing.Protocol` could be redefined to be your HPCPAPI. Every problem is now solved. Structural subtyping is now genuinely usable.
> 
> There's a caveat. If caching dramatically increases space complexity for downstream consumers in unexpected ways, the userbase will abandon @beartype after doxxing me on 4chan. That's bad. You've probably already tackled this concern (_...maybe with an internal LRU cache?_). If so, I have no remaining concerns and (with your generous permission and all the glory attributed directly to you as I abase myself before your complex throne of head-spinning protocols) will shortly assimilate your HPCPAPI into `beartype.typing.Protocol`. That's good.

Filing separately because #7 deals with a broader issue, and I got distracted by this shiny object.

**Comment by leycec** [comment]
When brilliance refracts itself through a prism that suspiciously resembles a [little-known album cover from a little-known 70's band whose name possibly rhymes with Blink Boyd](https://rateyourmusic.com/release/album/pink-floyd/the-dark-side-of-the-moon/), the above galaxy brain-tier post from @posita is what humanity gets. "DropBox, I summon you to pay this man in all of your corporate assets immediately!" <sup>*...fingers crossed*</sup>

> ...I can tackle a (rant-free²) PR as a starting point.

**This.** So much this. Actually, I'm delighted to hack at this, too – but currently preoccupied (to an unhealthy degree that our cats find disturbing yet compelling) with finalizing the upcoming beartype configuration API.

If we leave this to me, we leave this in the hands of Fate. Having read Pratchett, I trust Fate less than I used to.

> ...beartype's philosophy is to do what it can for various Python versions, falling back to less cool stuff where needed, but without imposing additional runtime dependencies.

**This.** In theory, silently integrating `typing_extensions` into `beartype.typing` without anyone noticing is on the beer-stained table. In practice, actually making that work without either `mypy` or `beartype` vomiting into its own sticky craw takes that back off the table.

Beartype: it cleans your table so you don't have to.

> Option 3 - `beartype.typing.Protocol` is the caching version

**This.** `beartype.typing.Protocol` solves everything so nobody ever has to suffer under the heavy load of `typing.Protocol` again.

Beartype: it takes the load right off you and puts it right on itself, because that's what caring and sharing means. :heart_on_fire: 

> My instinct says overrides (exposed via the `includes` and `excludes` methods) is a higher level feature that probably doesn't belong in `beartype`.

**This.** I'm fuming that `complex` dribbles all over the `isinstance()` builtin like a raving raccoon trash-digging through our mid-summer compost pile, but we'll *probably* have to pretend that never happened.

The overriding constraint for `beartype.typing` is that it preserve a one-to-one API mapping with `typing`. Thankfully, `numerary` exists to violate that mapping and fix all the mistakes of the inglorious past.

`numerary`: where I will drive *anyone* who complains about numeric type-checking to.

> `beartype and `numerary` each maintain their own implementations because they have different requirements...

**This.** I briefly contemplated refactoring `numerary` to subclass its own caching protocol implementation from `beartype.typing.Protocol`. Then I remembered the last five minutes of *Pi* as the refrain of a little-known 90's song rebounded through my earwax-laden canals: "Gotta keep 'em separated."

> I was just trying to sound smart.

**This.** So much this. You will be both pleased and horrified to learn that my wife insists (despite lingering doubts I share) that computing tensor densities on microcontrollers is now a thing that exists, because [NumPy has been ported to MicroPython and CircuitPython as a thing called `ulab`](https://github.com/v923z/micropython-ulab).

If She suspects I doubt, it will not go well with me tonight. I now go to gird my loins in preparation.

**Comment by posita** [comment]
> **This.** So much this. You will be both pleased and horrified to learn that my wife insists (despite lingering doubts I share) that computing tensor densities on microcontrollers is now a thing that exists, because [NumPy has been ported to MicroPython and CircuitPython as a thing called `ulab`](https://github.com/v923z/micropython-ulab).

The wonders never cease.

beartype/beartype#86 is now up, but should be considered a work in progress.

**Comment by posita** [comment]
_[Moved from #7, since I_ think _I finally understand the request(s).]_

# Discussion topic: How should we allow a cache limit to be tuned?

I know the subject of runtime configurability [has come up before](https://github.com/beartype/beartype/commit/8fd38b36b13f0e653785166dab3edc2892a03d6d#commitcomment-60594974). This one's tricksy. The temptation is to invite and set any limit override at load time, not at any arbitrary point at runtime. (The first thing that comes to mind is an environment variable?) I suppose we could expose an interface to `CachingProtocolMeta`, but we'd probably have to worry about thread-safety and all that stuff? Maybe not?

# Discussion topic: Should the LRU mechanism be [`CacheLruStrong`](https://github.com/beartype/beartype/blob/50b213f315ecf97ea6a42674defe474b8f5d7203/beartype/_util/cache/map/utilmaplru.py#L37) or something else?

[Cautions aside](https://github.com/beartype/beartype/blob/50b213f315ecf97ea6a42674defe474b8f5d7203/beartype/_util/cache/map/utilmaplru.py#L12-L29), I'm a huge fan of not reinventing wheels. I don't think strong references are an issue. (My assumption is that `Protocol`s are typically defined at the module scope and stay around forever, so there wouldn't be any benefit to weak-refs.) What I *am* a little nervous about ~~(perhaps unnecessarily, I haven't tested it)~~ is the locking overhead.

_FIRST UPDATE: I did some quick-and-dirty before/after testing where I replaced [`CachingProtocolMeta`'s non-guarded `dict`](https://github.com/posita/numerary/blob/dd57bffff32c8e1c4d46409c9302318bdcfe3e20/numerary/types.py#L190) with an instance of `CacheLruStrong(128)`._

<details>
<summary><code>perf_test.ipy</code></summary>

Carried over and tweaked from beartype/beartype#67.

``` python
# perf_test.ipy  # <-- that's IPython-speak for the uninitiated
from decimal import Decimal
from fractions import Fraction

import sympy

from numerary.types import SupportsComplexOps  # CachingProtocolMeta version
from numerary.types import _SupportsComplexOps  # non-caching version

# idealized baseline
# print(f"%timeit isinstance(1, int)")
# %timeit isinstance(1, int)
# print()

one_int = 1
two_float = 2.0
three_dec = Decimal(3)
four_frac = Fraction(4)
five_sym = sympy.sympify(5)
vals = (one_int, two_float, three_dec, four_frac, five_sym)

def supports_complex(arg: _SupportsComplexOps):
  assert isinstance(arg, _SupportsComplexOps)

def supports_complex_cached(arg: SupportsComplexOps):
  assert isinstance(arg, SupportsComplexOps)

for v in vals:
  for f in (supports_complex, supports_complex_cached):
    print(f"timing {f.__name__} with {v} ({type(v)})")
    %timeit f(v)
  print()
```

</details>

<details>
<summary>Before:</summary>

``` sh
% ipython perf_test.ipy
timing supports_complex with 1 (<class 'int'>)
9.78 µs ± 170 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 1 (<class 'int'>)
242 ns ± 1.59 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 2.0 (<class 'float'>)
9.94 µs ± 300 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 2.0 (<class 'float'>)
241 ns ± 0.486 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 3 (<class 'decimal.Decimal'>)
9.77 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 3 (<class 'decimal.Decimal'>)
244 ns ± 6.07 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 4 (<class 'fractions.Fraction'>)
9.74 µs ± 130 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 4 (<class 'fractions.Fraction'>)
249 ns ± 0.647 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 5 (<class 'sympy.core.numbers.Integer'>)
9.8 µs ± 125 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 5 (<class 'sympy.core.numbers.Integer'>)
251 ns ± 1.32 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

</details>

<details>
<summary>After:</summary>

``` sh
% ipython perf_test.ipy
timing supports_complex with 1 (<class 'int'>)
9.58 µs ± 129 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 1 (<class 'int'>)
878 ns ± 6.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 2.0 (<class 'float'>)
9.68 µs ± 164 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 2.0 (<class 'float'>)
884 ns ± 17 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 3 (<class 'decimal.Decimal'>)
9.68 µs ± 205 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 3 (<class 'decimal.Decimal'>)
890 ns ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 4 (<class 'fractions.Fraction'>)
9.73 µs ± 156 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 4 (<class 'fractions.Fraction'>)
880 ns ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 5 (<class 'sympy.core.numbers.Integer'>)
9.75 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 5 (<class 'sympy.core.numbers.Integer'>)
889 ns ± 28.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

</details>

Let's call it _around_ a 3× hit over my naive (admittedly non-thread safe) approach, but still a 10× improvement over not caching.

_SECOND UPDATE: I removed the `with self._lock:` contexts from `CacheLruStrong` and tested again to try to tease out the LRU logic from the locking overhead._

<details>
<summary>With LRU logic, but without locks:</summary>

``` sh
% ipython perf_test.ipy
timing supports_complex with 1 (<class 'int'>)
9.58 µs ± 69.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 1 (<class 'int'>)
632 ns ± 15 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 2.0 (<class 'float'>)
9.55 µs ± 161 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 2.0 (<class 'float'>)
618 ns ± 2.58 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 3 (<class 'decimal.Decimal'>)
9.56 µs ± 141 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 3 (<class 'decimal.Decimal'>)
623 ns ± 4.09 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 4 (<class 'fractions.Fraction'>)
9.55 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 4 (<class 'fractions.Fraction'>)
622 ns ± 7.43 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

timing supports_complex with 5 (<class 'sympy.core.numbers.Integer'>)
9.58 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
timing supports_complex_cached with 5 (<class 'sympy.core.numbers.Integer'>)
629 ns ± 8.22 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
</details>

Assuming my methodology was sound, _very_ roughly 250 ns is my naive base implementation, 250 ms is locks and 350-400 ns is LRU accounting.

_THIRD UPDATE (mostly tangential): After some casual reading, I don't think this is a strong case to revive beartype/beartype#31 (i.e., that we could use this exercise as an excuse to implement `LRUDuffleCacheStrong`). As far as I understand those motivations, they are targeted at keeping the aggregate size of cached entries within a boundary (vs. number of entries). We're caching `bool`s and references to `type`s here, number of entries should closely correlate with aggregate size. I might have misunderstood, though._

_FOURTH UPDATE: Food for thought on thread safe access of `dict`s…._

* https://docs.python.org/3/faq/library.html#what-kinds-of-global-value-mutation-are-thread-safe
* https://docs.python.org/3/glossary.html#term-global-interpreter-lock
* https://jython.readthedocs.io/en/latest/Concurrency/#java-or-python-apis
* https://stackoverflow.com/q/2291069

# Meta-discussion topic: Is a per-`Protocol` cache even the right approach? Should we consider a global one instead?

Under `numerary`'s current implementation, each `Protocol` maintains a separate cache of what types do and do not "comply" with its interfaces. I haven't thought this through, but I could see a case for creating a single global cache instead. I think it makes tunability and profiling much more important (especially if one is using the mechanism and also relying on a third party library that uses the same mechanism under the covers). My instinct is to keep the `Protocol`-scoped cache, but I wanted to throw this out there.

**Comment by posita** [comment]
By the way, for those playing our home game, [this](https://github.com/beartype/beartype/blob/50b213f315ecf97ea6a42674defe474b8f5d7203/beartype_test/a00_unit/a00_util/cache/pool/test_utilcachepoolobjecttyped.py#L32-L47) is an awesome public service announcement (with guitars).

**Comment by leycec** [comment]
**Amazing discussion continues amazing.**

## A Configuration API Arises from the Blackest Depths of Moria

Firstly, the public gala unveiling the beartype configuration API is happening now and you're the only one invited: <sup>*squeeeee*</sup>

``` python
from beartype import beartype, BeartypeConf, BeartypeStrategy

# Configure @beartype to do all these things:
# * Type-check everything in O(n) linear time.
#   This is currently ignored. So, we're still gonna
#   type-check a single thing in O(1) constant time.
#   This is the cost of personal sloth and pizza.
# * Print the signature and body of the
#   type-checking wrapper function dynamically
#   generated by @beartype here to stdout.
@beartype(conf=BeartypeConf(
    strategy=BeartypeStrategy.On,
    is_print_wrapper_code=True,
))
def public_service_announcement(with_guitars: list[str]) -> None:
    print('These are your rights:\n' + '\n'.join(with_guitars))
```

@beartype: freedom may still not be free, but at least we can type-check it.

Given `beartype.BeartypeConf`, we absolutely can, should, and must stuff everything (including that leaky kitchen sink we haven't cleaned in five years according to an annoying calendar app) that is configurable into that class. See the [super-secret `beartype._decor.conf` submodule that has a license to kill...](https://github.com/beartype/beartype/blob/main/beartype/_decor/conf.py) *bugs*, that is. :drum: 

But first...

## Safe Threads Make Safe Sweaters

Secondly, **thread-safety.**

The :bulb: realization I've had over the past several lifetimes as a poorly paid techbro is that thread safety only *really* matters when the consequences of violating thread-safety are both harmful and permanent – like collapsing into a snow drift five yards from our cabin's front door without double mittens on, which is not gonna end well. Thankfully, that's basically never the case for memoization, caching, or other optimizations.

For caching, violating thread-safety usually just means that contesting threads repeatedly cache the same thing as they trip over each trying to get out of a snow drift five yards from our cabin's front door without double mittens on. That's usually fine. Is that fine here? I know nothing, but kinda suspect we're better off *without* lugging around a giant deadweight `self._lock` everywhere.

## Less Work Means Less Migraines

> My instinct is to keep the `Protocol`-scoped cache...

Thirdly, my instinct is to keep following your instinct. Instinctual recursion: *engage!*

We do as you say in all things. Lastly...

## How Much Space Are We Talkin' Here?

Since...

> We're caching `bool`s and references to `type`s here...

...we may not even need to deep-dive into LRU caching here. I know, right? I'm squeeing again over here. Specifically:

* `bool` is `int`, and Python interns (i.e., reduces to singletons) all integers in the range `[0, 255]`; since booleans are integers in the range `[0, 1]`, Python thus interns all booleans. Basically no space consumption there.
* Likewise, classes are typically module-scoped (exactly as you say) and thus preserved in memory for the process lifetime. Yet again, basically no space consumption there either.

<sub>What fearsomely heroic magic is this!?!?</sub>

My festering guts are insinuating that LRU caching might be overkill here. What say you before faceplanting into the nearest cushion with unspeakable exhaustion, Typing Overlord Posita?

**Comment by posita** [comment]
beartype/beartype#117 aside (which I hope I didn't cause), I think we can call this fixed by beartype/beartype#86 and beartype/beartype#103?

**Comment by leycec** [comment]
**Jolly good show,** bear bro! I meant to close this out for you a few weeks ago, but then Russia repeatedly blew up Ukraine and all I ended up doing was wearing out my `<F5>` key on [/r/Ukraine](https://reddit.com/r/Ukraine).

Thanks again for all that fast-actin' protocol cachin'. I'm [currently hip-deep wading through the uncomposted manure that is Sphinx configuration](https://github.com/beartype/beartype/issues/8#issuecomment-1088354012). This is why I've been quiet on the @beartype and `numerary` front. Sphinx is the pain that assaults my brain.

Please, *please*, **_please_** drop me a line at any time if `numerary` has any further needs *or* invents any further piles of code gold that we can run away with and pretend were ours all along. :smirk:

**Comment by posita** [comment]
Sphinx. Yes. Ugh. Your observations are apt. Getting Sphinx to work is like "implementing" SAP (which is one of those rare cases where I think "implement" is the right word to describe a software installation¹). I used to fight with it on all my projects, including well after the getting-it-up-and-running phase. RtD was cool, but finicky. (I hope that's changed.) Sphinx and rST is precisely the reason I now use MkDocs (with [Material](https://squidfunk.github.io/mkdocs-material/)) and Markdown. (No more RtD integration. I now publish straight to GitHub pages for each release, although I haven't yet invested the time to automate this.) It hasn't been [without issue](https://github.com/squidfunk/mkdocs-material/issues?q=author%3Aposita), and I gave up a lot of shiny promises with Sphinx², but I didn't use those anyway, and I'm much happier.

I would offer to assist, but I've long since forgotten (or willfully suppressed) any memory around my troubles with Sphinx. You're welcome to ask me for help at any time. I just can't guarantee I'll be useful. Heck, I can't guarantee I won't be involuntarily triggered into a weeping mess to be scooped up off the floor with a spatula. But I'm willing to give it a shot.

¹ Hint: if I need to "implement" your software in order to use it, you don't have not delivered a product. You have delivered a liability. But, hey, what do I know?

² I mean who _hasn't_ dreamed of a single documenting system that supports multi-language cross-references?

**Comment by posita** [comment]
Oh! One thing that did occur to me is that caching protocols _may_ have value orthogonal to beartype. This may make runtime beartype configuration (which is a subject I know you've given some thought) more useful. Consider, for example, the case where one wants to start retrofitting the `@beartype` decorator to a large codebase _and_ to pick up the benefits of caching protocols. A desirable approach might be to start using the decorator incrementally in CI, but not in production while using caching protocols everywhere. `numerary` inartfully walks that line by [requiring an environment variable to be set](https://github.com/posita/numerary/blob/main/numerary/bt.py) in order to "activate" the `@beartype` decorator in its own codebase. There are probably better approaches.

**Comment by leycec** [comment]
> SAP

Enterprise JavaBeans PTSD intensifies. It's best for both of us that we not relive those hateful memories.

> ...if I need to "implement" your software in order to use it, you don't have not delivered a product. You have delivered a liability.

Quoted for truth. Animated for feels.

![this is me](https://c.tenor.com/eBByy4ihCocAAAAC/angry-fist.gif)

> ...MkDocs (with [Material](https://squidfunk.github.io/mkdocs-material/)) and Markdown...

Keep selling me on this. I'm an easy customer here, because my black heart is already filled with vengeance at the vendor I'm locked in with what feels suspiciously like a straightjacket.

> ...publish straight to GitHub pages...

**Sold.** Static site generators is my jam – or would be, if I webdeved. Which I totally could. You know. Like... any minute. `<crickets_chirp/>`

Sadly, I'm reliving 90's flashbacks of "I'm a Teenage Dirtbag." So, not teenage but a dirtbag? Long Grecian tragedy story short (that could very well end with someone depravedly clawing out their own sensory apparatus): @beartype has so much content locked up in reStructuredText – including a literal dumpster's worth of embedded docstrings and a `README.rst` that frightens even Pandoc (and *nothing* frightens Pandoc) – that abandoning Sphinx for verdant fields elsewhere is *probably* a non-starter.

I value my sanity, so I wish that abandoning Sphinx was a starter. MkDocs + Material + GitHub Pages: *take me now!*

The only winning move is not to play. We all remember hearing that somewhere. Now, we are living that moment.

> A desirable approach might be to start using the decorator incrementally in CI, but not in production...

**Bwaha!** Code or it didn't happen, so:

```python
from beartype import (
    BeartypeConf, BeartypeStrategy, beartype)

beartype_conf = BeartypeConf(
    strategy=(
        BeartypeStrategy.O0  # <-- no-time is a thing
        if MUH_BURNING_PRODUCTION_LINE else
        BeartypeStrategy.O1  # <-- linear-time for justice
    )
)
'''
Beartype configuration suitable for the current environment.
Specifically:

* On production, this configuration currently disables the
  :func:`beartype.beartype` decorator entirely.
* On CI, this configuration enables the default ``O(1)``-time
  :func:`beartype.beartype` decorator behaviour.
'''

@beartype(conf=beartype_conf)
def make_it_so_number_one() -> str:
    return 'My beard despises you, Jean Luc.'
```

Relatedly, German Megamind @amogorkon recently invented [this *phenomenal* Python swag called `justuse`](https://github.com/amogorkon/justuse/issues/141) that lets you violently decorate all callables defined by any arbitrary module with `@beartype` at any arbitrary time:

```python
import beartype, numpy, use

# Type-check the entire NumPy API with @beartype.
use.apply_aspect(numpy, beartype)

# Type-check @beartype itself with @beartype.
use.apply_aspect(beartype, beartype)

# Type-check your production line with @beartype
# using the aforementioned configuration. Hazzuh!
import burn_it_down
use.apply_aspect(burn_it_down, beartype(conf=beartype_conf))
```

Apparently, Rome *was* built in a day. :stadium:
